### ISSUE TITLE
org-projectile:known-projects shouldn't load remote projects

### ISSUE THREAD

**Issue by Mekk** [IvanMalison/org-projectile#10]
My attempts to call `org-projectile:project-todo-completing-read` take long time, ask passwords (and then end up in crash which may be related, or not).  The reason is that they include remote (scp) paths for remote repositories I happened to open in the past.

There are two parts of this issue:
- (easier) org-projectile:project-root-of-filepath could limit itself to local paths
- (harder) the whole idea of org-projectile:project-root-of-filepath scanning complete projectile-project-root-cache is controversial; in my case `projectile-project-root-cache` has more than hundred items including more than 10 remote (tramp) items

**Comment by IvanMalison** [comment]
I feel like this is more of an issue with projectile than with org-projectile. You should have the same issue when switchign to a project wiht projectile.

**Comment by Mekk** [comment]
projectile does not acess the path until I pick it, it uses the list on purely textual basis. I didn't read the code but it never asked me for remote ssh password (unless I actually picked remote project).

**Comment by IvanMalison** [comment]
I see. I think that the password prompts come from when we run file-truename on the path. This is still something I would like to do, but ill try to come up with a way to avoid this.

**Comment by IvanMalison** [comment]
@Mekk I added an option that is enabled by default that skips over projects that require any special access. Things should work now.
