### ISSUE TITLE
Helm requirement

### ISSUE THREAD

**Issue by jtamagnan** [IvanMalison/org-projectile#15]
It seems like this project recently started depending on and installing helm. It seems like all of the helm code is used to add the `org-projectile:template-or-project` function would it be possible to place all relevant helm code in a block like: 
```
(when (require 'helm nil 'noerror)
  .
  .
  .
  )
```
and then remove the dependency?

**Comment by IvanMalison** [comment]
Sure. The reason the helm requirement was added is that it is needed at compile time, but i suppose that this approach would work as well

**Comment by jtamagnan** [comment]
There also seems to be an issue with the current build. If 'helm-org is not required then `helm-source-org-capture-templates` is not defined and therefore `org-projectile:template-or-project` will not be properly created. I tried this with the melpa version and emacs -Q. There is a pull request fixing this issue and removing helm as a requirement upcoming shortly

**Comment by jtamagnan** [comment]
The related push is #16
