### ISSUE TITLE
Per-repo mode gives nested headings

### ISSUE THREAD

**Issue by TheBB** [IvanMalison/org-projectile#17]
I'm using `(org-projectile:per-repo)` and after capturing three test todos this is the result

```
*** TODO First entry
***** TODO Second entry
******* TODO Third entry
```

As you can see the headings become nested. I don't think this is intentional?

**Comment by IvanMalison** [comment]
Thanks for the report. I'm not currently able to replicate the issue. Can you post additional details about your configuration including:

org/emacs version
org configuration

etc.

**Comment by TheBB** [comment]
Hi again, sorry for the delay. I'm working on putting this in Spacemacs instead of org-repo-todo. I've been able to reproduce this on Org 8.3.4 with no additional configuration other than:

```elisp
(require 'org-projectile)
(org-projectile:per-repo)
(setq org-projectile:per-repo-filename "TODOs.org")
(setq org-agenda-files (append org-agenda-files (org-projectile:todo-files)))
```

The sample configuration in the README for non-per-project TODO files also appears not to work as intended. All the entries become top-level. That also with org 8.3.4.

Just now I tried with Org 8.2.10 and it appears to reproduce just fine there too.

**Comment by IvanMalison** [comment]
> I'm working on putting this in Spacemacs instead of org-repo-todo.

oh cool. thats exciting

Thanks for the sample config. I'll try to replicate the issue and see if I can tease apart what is going on

**Comment by IvanMalison** [comment]
Looks like this bug was introduced in 23c692c1e740b65d099011f68d90377ef7481302

I'm working on a quick hack to fix this right now. Unfortunately the code is going to be really ugly (as a lot of the org-projectile code is, because the original org-capture code was not written in a very modular way).

**Comment by TheBB** [comment]
Yeah, I've noticed. :-/

Thanks for taking a look.

**Comment by IvanMalison** [comment]
@TheBB can you verify that things are working for you?

**Comment by TheBB** [comment]
Yep, it's fine now. Thanks!
