### ISSUE TITLE
Byte compiling error: void variable: occ-build-capture-template (broken in emacs 24)

### ISSUE THREAD

**Issue by et2010** [IvanMalison/org-projectile#22]
While installing org-projectile via melpa, I got this error:

`org-projectile.el:33:1:Error: Symbol's value as variable is void: occ-build-capture-template`

The same problem happens when I try to byte compile `org-projectile.el` or load `org-category-capture.el`.

edit:
I removed all the `elc` file, and try to load the uncompiled `org-category-capture.el`. This time the error message is a little different:

`Symbol's function definition is void: cl-defmethod`

It seems that `eieio` only provides the macro `defmethod`.

**Comment by IvanMalison** [comment]
ah are you using emacs24 or 25?

**Comment by et2010** [comment]
I'm using 24

**Comment by IvanMalison** [comment]
okay, damn. yeah let me see if I can get this working in 24 again. Thanks for the report.

**Comment by samspills** [comment]
Hey! I was struggling with this (also on emacs 24), and switching line 57 of org-category-capture.el to `defmethod` instead of `cl-defmethod` fixed the issue and didn't seem to have any negative side-effects. 

Still sort of new to lisp though, not sure if that's a good solution.

**Comment by IvanMalison** [comment]
well the problem is that with certain optional arguments this will not work. I'm going to try to do something a little better than that.

**Comment by IvanMalison** [comment]
@samspills @et2010 I can't even seem to get this to fail in 24.4.

Can you guys give me the exact version numbers of emacs you guys are on?

**Comment by samspills** [comment]
#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git org markdown
                 (shell :variables shell-default-shell 'multi-term shell-default-term-shell "/bin/zsh")
                 syntax-checking python scala)
```

**Comment by IvanMalison** [comment]
Success -- failed travis CI:
https://travis-ci.org/IvanMalison/org-projectile/jobs/173139097

Now to fix.

**Comment by IvanMalison** [comment]
Build is green https://travis-ci.org/IvanMalison/org-projectile/builds/173140271

You'll need to wait for a bit for this to land on melpa...
