### ISSUE TITLE
Obsolete usage of pcache-repository

### ISSUE THREAD

**Issue by mdorman** [IvanMalison/org-projectile#24]
We're throwing a warning; I suspect, based on sigma/pcache#5, that it's been going on for at least most of a year:

```
../../nix/store/235adcshf0l8zf90qa9j93m3yj73xrb9-emacs-packages-deps/share/emacs/site-lisp/elpa/org-projectile-0.2.5/org-projectile.el: Obsolete name arg "org-projectile:path-to-category" to constructor pcache-repository
```

**Comment by IvanMalison** [comment]
Yeah, and org-projectile isn't even using pcache currently, I don't think.

**Comment by mdorman** [comment]
Hadn't even noticed that.  Added #25 to resolve it by removing the reference.
