### ISSUE TITLE
Failure in org-projectile:project-todo-completing-read

### ISSUE THREAD

**Issue by yyadavalli** [IvanMalison/org-projectile#27]
Invocation of `org-projectile:project-todo-completing-read` fails with the following message.

```
projectile-completing-read: Keyword argument * TODO %?
 not one of (:initial-input :action)
```

Looks like the `make-instance` is not setup correctly here
https://github.com/IvanMalison/org-projectile/blob/master/org-projectile.el#L561

**Comment by IvanMalison** [comment]
@yyadavalli let me know if that fix works for you

**Comment by yyadavalli** [comment]
Thanks for the quick response.

I am able create the TODO now, but after closing the capture buffer, the `projects.org` buffer is left open instead of going back to the buffer I started from.

I am not sure if this is a side effect of my personal configuration.

**Comment by IvanMalison** [comment]
oh hmmm, yeah I see that behavior as well. let me take a look.
