### ISSUE TITLE
Getting error "org-projectile:insert-or-goto-heading: Wrong number of arguments: #[(&optional arg invisible-ok)"

### ISSUE THREAD

**Issue by vmalloc** [IvanMalison/org-projectile#29]

**Comment by IvanMalison** [comment]
Can you provide some additional details?

What version are you using? When does this happen? Do you have a reliable repro?

**Comment by vmalloc** [comment]
After closer inspection it seems to have happened because I wasn't using the latest version of org-mode. Sorry for the trouble!
