### ISSUE TITLE
`(org-projectile-per-repo)` produces error

### ISSUE THREAD

**Issue by yatesco** [IvanMalison/org-projectile#31]
On the latest package `(org-projectile-per-repo)` throws a Symbol void error.

To reproduce, install `org-projectile` and then eval the following (note: copied from the README):
``` emacs-lisp
(require 'org-projectile)
(org-projectile-per-repo)
(setq org-projectile-per-project-filepath "my_project_todo_filename.org")
(setq org-agenda-files (append org-agenda-files (org-projectile-todo-files)))
(global-set-key (kbd "C-c c") 'org-capture)
(global-set-key (kbd "C-c n p") 'org-projectile-project-todo-completing-read)
```

**Comment by IvanMalison** [comment]
Yeah, sorry, That function no longer exists. I just added a function (org-projectile-per-project) that will do the same thing.

**Comment by yatesco** [comment]
No worries, shall I do a PR to update the front page?

**Comment by IvanMalison** [comment]
I already did, I think

**Comment by IvanMalison** [comment]
were you able to get the new version of org-projectile and see if it works for you?

**Comment by yatesco** [comment]
Apologies - you did already :-). Thanks for the quick turn around, I will check tomorrow when I get back to the computer.
--
  Colin Yates
  colin@colinyates.co.uk



On Sat, 29 Jul 2017, at 10:21 PM, Ivan Malison wrote:
> were you able to get the new version of org-projectile and see if it works for you?> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2]. > 

Links:

  1. https://github.com/IvanMalison/org-projectile/issues/31#issuecomment-318860440

**Comment by yatesco** [comment]
Works perfectly - thanks.
