### ISSUE TITLE
Creating a TODO fails with error 'Wrong type argument: number-or-marker-p, nil'

### ISSUE THREAD

**Issue by yyadavalli** [IvanMalison/org-projectile#33]
This is true for both
 `org-projectile-project-todo-completing-read` and `org-projectile-capture-for-current-project`

I was not able to find anything by debugging. Any pointers would be appreciated.

**Comment by IvanMalison** [comment]
can you toggle-debug-on-error to get a backtrace?

**Comment by yyadavalli** [comment]
Sorry I forgot to post it earlier
[test.txt](https://github.com/IvanMalison/org-projectile/files/1236058/test.txt)

**Comment by IvanMalison** [comment]
Do you have the very latest version?

Is the file you are targeting an org-mode file?

**Comment by yyadavalli** [comment]
Yes and yes.

**Comment by IvanMalison** [comment]
Can you go to the relevant line in the source
and change it to 
```
(1+ (or (org-current-level) 0))
```

I'm pretty sure that this will sort of fix your problem, but that function should not be returning nil if the file is actually in org-mode.

**Comment by IvanMalison** [comment]
@yyadavalli let me know if this fixed your issue.

**Comment by yyadavalli** [comment]
@IvanMalison This fixed the issue. Thanks for the amazing response.
