### ISSUE TITLE
Org-projectile-linked-capture-template on Spacemacs

### ISSUE THREAD

**Issue by PrestanceDesign** [IvanMalison/org-projectile#34]
Hi,

I use Spacemacs and I don't know how to using the capture template **org-projectile-linked-capture-template**.
The goal is to use it to link TODO keyword on source code like **org-store-link** did. It's possible ?

Best regards.

**Comment by IvanMalison** [comment]
Both `org-projectile-capture-for-current-project` and `org-projectile-project-todo-completing-read` take an optional capture template argument.

I think that it used to be that there was an interactive function that would use org-projectile-linked-capture-template depending on whether or not the prefix argument was sent, but it no longer exists.

**Comment by PrestanceDesign** [comment]
OK thx for the information. :+1: 

Cheers.
