### ISSUE TITLE
Select project for TODO capture?

### ISSUE THREAD

**Issue by chase-dwelle** [IvanMalison/org-projectile#38]
Is it possible to select the projectile project that you want to capture the task for? I am using a project-specific `TODOS.org` file in each projectile directory.

I don't know if this is the intended functionality, but in order to capture a TODO for a project, I need to call capture from an emacs buffer that has a file open within that project directory. I would like to capture a task from any buffer in any directory, and be able to choose which project it files into. The default option should be the current projectile project, if avaiable, but give the option to choose another project if that is desired.

**Comment by IvanMalison** [comment]
`org-projectile-project-todo-completing-read`
