### ISSUE TITLE
How to set path for specific projects in org-projectile-per-project mode ?

### ISSUE THREAD

**Issue by scarletsky** [IvanMalison/org-projectile#39]
Hi, I am a `org-projectile-per-project` user.
I'd like to add an org file to the root of  my personal projects. That is:

```
.
├── .git
├── package.json
├── src
└── TODOs.org
```

But in my company projects, I need to add it to sub folders.

```
├── .git
├── backend
└── frontend
    ├── src
    ├── package.json
    └── TODOs.org
```

How can I set it ?

**Comment by scarletsky** [comment]
Wow, thanks for your quick replay ! 
I've checked the commit, I think the usage should be

```
(org-projectile-per-project-filepath
 (lambda (path)
   (if (string-equal path "/sp-project")
       "OTHER.org"
     "TODO.org"))))
```

Right ?

**Comment by IvanMalison** [comment]
@scarletsky 

```
(setq org-projectile-per-project-filepath
 (lambda (path)
   (if (string-equal path "/sp-project")
       "special_location_TODOS/TODO.org"
     "TODO.org"))))
```

Yes, although I'm assuming you'll want more than just "Is it equal to this one specific project" as your condition (or maybe that is all you need)?

**Comment by scarletsky** [comment]
@IvanMalison Yes, I can extend the sp-projects list myself. Thanks. 😄
