### ISSUE TITLE
Don't run file-truename on nil (handle deleted projects gracefully)

### ISSUE THREAD

**Issue by IvanMalison** [IvanMalison/org-projectile#7]
** TODO Don't run file-truename on nil (handle deleted projects gracefully)
#+BEGIN_SRC
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  file-truename(nil)
  org-projectile:project-root-of-filepath("~/")
  org-projectile:project-heading-from-file("~/")
  mapcar(org-projectile:project-heading-from-file ("~/Uber/supply/" "~/Dropbox (Personal)/" "~/Projects/.emacs.d/" "~/dotfiles/" "~/Uber/flipr/" "~/" "~/Projects/sync/" "~/Projects/sku_authority/" "~/Uber/demand/" "/usr/local/" "~/Uber/sync/STUDEBAKER-D350-2.dev.uber.com/home/uber/api/" "~/Projects/realtime-api/" "~/Uber/inventory_management/" "~/Uber/disco/" "~/Projects/merchpbx/" "~/Projects/vcrpy/" "~/backups/dispatch/" "~/Projects/restclient.el/" "~/Projects/org-projectile/" "~/Projects/okcupyd/" "~/Projects/eats_demand/" "~/Projects/geospatial2/" "~/Projects/clay-sqlalchemy/" "~/Projects/clay/" "~/Projects/spacemacs/" "~/Projects/slash_grid/" "~/Projects/inventory-management-client/" "~/Projects/dotfiles/" "~/Uber/uber-engi-dotfiles/" "~/Projects/geofence/" "~/Projects/projectile/" "~/Projects/goldeta/" "~/Projects/tornado/" "~/Projects/ncar/" "~/Projects/man-in-the-muni/" "~/Projects/cleopatra/" "~/Projects/tern/" "~/Projects/optic/" "~/Uber/sync/nissan-avanti-5.dev.uber.com/home/uber/dispatch/" "~/Projects/optic-client/" "~/Uber/sync/nissan-avanti-5.dev.uber.com/home/uber/rtapi/" "~/Projects/boxer/"))
  org-projectile:known-projects()
  org-projectile:helm-source("* TODO %?\n  :LOGBOOK:  \n  - State \"TODO\"       from \"\"           [2015-07-24 Fri 22:27]\n  :END:      \n  :PROPERTIES:\n  :CREATED:  [2015-07-24 Fri 22:27]\n  :END:\n")
  (list (helm-source-org-capture-templates) (org-projectile:helm-source (if arg (org-capture-make-linked-todo-template) (org-capture-make-todo-template))))
  (helm :sources (list (helm-source-org-capture-templates) (org-projectile:helm-source (if arg (org-capture-make-linked-todo-template) (org-capture-make-todo-template)))) :candidate-number-limit 99999 :buffer "*helm org capture templates*")
  imalison:helm-org-todo(nil)
  call-interactively(imalison:helm-org-todo nil nil)
  command-execute(imalison:helm-org-todo)
#+END_SRC
   :LOGBOOK:
   - State "TODO"       from ""           [2015-07-24 Fri 22:29]
   :END:      
   :PROPERTIES:
   :CREATED:  [2015-07-24 Fri 22:29]
   :END:

**Comment by Mekk** [comment]
I faced this error. In my case ("/tmp/ble" was temporary mercurial repo which I dropped but which still is remembered by projectile).

```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  file-truename(nil)
  org-projectile:project-root-of-filepath("/tmp/ble/")
  org-projectile:project-heading-from-file("/tmp/ble/")
  mapcar(org-projectile:project-heading-from-file (… my list of various repositories …))
  org-projectile:known-projects()
  org-projectile:project-todo-completing-read()
  call-interactively(org-projectile:project-todo-completing-read nil nil)
  command-execute(org-projectile:project-todo-completing-read)
```

**Comment by Mekk** [comment]
The following fix helps

```diff
--- a/elpa/org-projectile-0.2.0/org-projectile.el	Tue Nov 03 08:57:20 2015 +0100
+++ b/elpa/org-projectile-0.2.0/org-projectile.el	Tue Nov 03 09:10:21 2015 +0100
@@ -31,6 +31,7 @@
 
 (require 'org-capture)
 (require 'projectile)
+(require 'cl)
 
 (defvar org-projectile:projects-file "~/org/projects.org")
 (defvar org-projectile:per-repo-filename "todo.org")
@@ -271,7 +272,7 @@
 
 (defun org-projectile:known-projects ()
   (delete-dups `(,@(mapcar #'org-projectile:project-heading-from-file
-                           (projectile-relevant-known-projects))
+                           (remove-if-not #'file-exists-p (projectile-relevant-known-projects)))
                  ,@(org-map-entries
                     (lambda () (org-projectile:get-link-description (nth 4 (org-heading-components)))) nil
                     (funcall org-projectile:todo-files)
